# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [95]:
import numpy as np
my_array=np.array(range(0,10))
print(my_array[-1:-10:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [96]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [97]:
print(my_array[-8::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [98]:
a=np.arange(1, 21, 1).reshape(4,5)
print(a)
a[::-1,::-1] #asi paradarle la vuelta dos a filas y columnas, si le hago solo uno me cambia las filas

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [99]:
a=np.arange(1, 21, 1)

array_2=a[0:2]
array_3=a[5:7]
np.concatenate(([array_2], [array_3])) #primera forma
a1=np.concatenate([[a[0:2],a[5:7]]]) #otra forma de hacerlo
a1

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [105]:
array_4=a[0:6:2]
array_5=a[10:16:2]
np.concatenate(([array_4], [array_5]))

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [106]:
array_6=a[4::-1]
array_7=a[9:4:-1]
array_8=a[14:9:-1]
np.concatenate(([array_6], [array_7],[array_8]))
a1=np.concatenate([[a[4::-1],a[9:4:-1],a[14:9:-1]]])
a1

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x_bools = x == "Loro"
print(x[x_bools])


['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [12]:
y = np.arange(20).reshape(5,2,2)
y


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [16]:
z=a[-1:-6:-1]
m=a[-6:-11:-1]
n=a[-11:-16:-1]
b=a[-16::-1]
np.concatenate(([z],[m],[n],[b]))

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [169]:
a=np.zeros(10)
print(a)
a.nbytes

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


80

In [22]:
a[3]=1

In [170]:
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [25]:
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [183]:
array_10=np.array([1,2,0,0,4,0])
indices = np.where(array_10)
print(indices)
print(indices[0])



(array([0, 1, 4], dtype=int64),)
[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [77]:
 j=np.random.uniform(0,10,(10,10))
print(len(j))
print(len(j[0]))
print(j)
np.min(j), np.max(j)

10
10
[[3.14182506 0.95766742 8.31556753 5.25422973 6.75943336 9.82454519
  1.40319399 8.28103817 0.09030961 9.45403084]
 [9.38023196 2.92844583 3.29532658 5.11462056 8.90322435 8.42055631
  6.41670398 3.84970629 2.43936963 5.49560622]
 [5.50069906 2.87612372 2.59216038 9.73950678 0.20002595 3.80909248
  8.37998294 7.47501388 9.72323128 4.91908469]
 [8.41394652 0.77628126 9.25491555 4.10728859 3.34114752 8.57538369
  6.38181642 0.86555503 8.80293003 5.67637868]
 [9.06014319 7.66392638 8.73609487 3.76759505 0.50015063 5.3733783
  1.09866136 6.14151802 3.00332259 0.93406981]
 [8.10946892 3.39198455 5.73180057 6.10510523 0.03956443 7.49831584
  6.62283341 3.45608241 2.66704056 1.03833106]
 [7.42378546 4.83547128 4.10495502 3.53597098 5.90743308 3.14417693
  0.1451561  2.31223547 7.60408128 2.73072503]
 [9.03528284 2.41098168 9.11474847 4.49366066 7.45303424 3.85711566
  9.97444012 0.82416899 4.77769824 1.18016507]
 [9.2232154  8.36111507 7.91276902 2.23377406 5.38209465 8.46460067
  1.633

(0.03956443074586091, 9.974440119566538)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [81]:
 h=np.random.uniform(0,10,(30))
 print(h)
 np.median(h)

[0.85905142 1.51678274 5.21066775 8.59517479 1.1368521  9.58842638
 8.81163647 1.80007409 5.29459306 7.33441114 8.0849575  5.5859483
 3.8488091  7.55111338 0.9684358  9.44589409 0.27832911 4.79743748
 4.28657828 7.52322095 1.05663995 7.10609281 9.01662046 0.17168511
 5.78297913 7.17597958 7.1487808  8.32977945 6.09249942 2.69535359]


5.684463714790204

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [121]:
x=np.ones((5,5))
x
x[1:-1,1:-1]=0  #desde la fila uno hasta la fila -1 y de la columna 1 hasta la columna -1 
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [185]:
t=np.zeros((8,8))

t[::2,1::2]=1
t[1::2,::2]=1
print(t)




[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [165]:
a=np.array([[0,1]])
c=np.array([[1,0]])
d=np.concatenate((a,c),axis=0)
b=np.tile(d,[4,4])
print(b)
print(len(b))
print(len(b[0]))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
8
8


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [196]:
 po=np.random.uniform(0,10,(5,5))
 print(po)
h=po.mean()
i=po.std()
normalizar=(po-h)/i
print(normalizar)

[[1.42060555 3.22288193 6.04423253 7.78450662 4.81696982]
 [2.77584685 2.43991571 6.12873566 1.48526372 3.19432794]
 [4.50417853 3.15395227 9.51938395 3.18865133 6.46594221]
 [4.81327318 5.79587116 2.13371423 5.44466436 2.90633475]
 [7.4510283  6.6172028  4.94399908 5.33780457 7.24975985]]
[[-1.59992043 -0.73477294  0.61956118  1.45494568  0.03043774]
 [-0.94936338 -1.11062054  0.66012525 -1.56888254 -0.74847972]
 [-0.1197116  -0.76786128  2.28773958 -0.75120467  0.82199466]
 [ 0.02866324  0.50034017 -1.25760657  0.33175022 -0.88672522]
 [ 1.29486595  0.89460434  0.09141565  0.28045427  1.19825097]]



## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [210]:
secuencia = np.arange(0,11,1)
secuencia[2:8] = -1
np.arraysecuencia_bools = secuencia != -1
secuencia_bools


array([ True,  True, False, False, False, False, False, False,  True,
        True,  True])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.